### ISSUE TITLE
Fix issue with the retry hook isn't triggered

### ISSUE THREAD

**Issue by vpetersson** [Screenly/Anthias#1756]
We currently have this structure in   our `[build_docker.yaml`](https://github.com/Screenly/Anthias/blob/master/.github/workflows/docker-build.yaml):

```yaml
      - uses: balena-io/deploy-to-balena-action@master
        id: build
        continue-on-error: true
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: screenly_ose/anthias-${{ matrix.board }}
          source: balena-deploy

      - name: Sleep random sleep before retry
        if: ${{ failure() && steps.build.conclusion == 'failure' }}
        run: |
          sleep $((120 + RANDOM % 900));
      # Balena deploy often fails with 'ESOCKETTIMEDOUT'.
      # This adds some retry logic.
      - uses: balena-io/deploy-to-balena-action@master
        id: build-retry
        if: ${{ failure() && steps.build.conclusion == 'failure' }}
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: screenly_ose/anthias-${{ matrix.board }}
          source: balena-deploy
```
In theory, this should trigger a retry if the balena deploy However, for whatever reason, it doesn't:

<img width="690" alt="Screenshot 2023-02-27 at 8 08 27 AM" src="https://user-images.githubusercontent.com/357664/221497134-a3239c03-6a00-4c8d-9c90-347faef87f9c.png">
